/*
 * Copyright 2026 Larder Software Limited
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * @typedef {object} RelationshipSeed
 * @property {string} name
 * @property {string} description
 * @property {string} sourceSeedName
 * @property {string} targetSeedName
 * @property {'field-matching'} strategy
 * @property {import('@roadiehq/catalog-datastore-common').RelationshipRuleMatchStrategy} matchStrategy
 * @property {string} sourceFieldExpression
 * @property {string} targetFieldExpression
 * @property {string} relationshipType
 * @property {string} [reciprocalRelationshipType]
 */

/**
 * @returns {RelationshipSeed[]}
 */
function getRelationshipSeeds() {
  return [
    require('./github-repos-collaborators'),
    require('./github-org-teams'),
    require('./github-org-members'),
    require('./github-repo-pull-requests'),
    require('./github-repo-merged-pull-requests'),
    ...require('./github-merged-pull-request-variants'),
    require('./github-repo-releases'),
    require('./github-repo-actions'),
    require('./github-repo-dependabot'),
    require('./github-team-teams'),
    require('./github-team-organization-members'),
    require('./github-repo-catalog-info-files'),
    require('./github-repo-yaml-files'),
    require('./github-repo-markdown-files'),
    require('./github-org-members-collaborators'),
    require('./github-org-members-pull-requests'),
    require('./github-org-members-releases'),
    require('./github-token-repos-app-repos'),
    require('./github-app-repos-collaborators'),
    require('./github-app-repo-pull-requests'),
    require('./github-app-repo-releases'),
    require('./github-app-repo-actions'),
    require('./github-app-repo-dependabot'),
    require('./github-app-repo-markdown-files'),
    require('./github-app-repo-yaml-files'),
    require('./github-app-team-organization-members'),
    require('./github-enterprise-repos-collaborators'),
    require('./github-enterprise-org-teams'),
    require('./github-enterprise-org-members'),
    require('./github-enterprise-repo-pull-requests'),
    require('./github-enterprise-repo-releases'),
    require('./github-enterprise-repo-actions'),
    require('./github-enterprise-repo-dependabot'),
    require('./github-enterprise-team-teams'),
    require('./github-enterprise-team-organization-members'),
    require('./github-enterprise-repo-catalog-info-files'),
    require('./github-enterprise-repo-yaml-files'),
    require('./github-enterprise-repo-markdown-files'),
    require('./github-enterprise-org-members-collaborators'),
    require('./github-enterprise-org-members-pull-requests'),
    require('./github-enterprise-org-members-releases'),
    require('./github-enterprise-token-repos-app-repos'),
    require('./github-enterprise-app-repos-collaborators'),
    require('./github-enterprise-app-repo-pull-requests'),
    require('./github-enterprise-app-repo-releases'),
    require('./github-enterprise-app-repo-actions'),
    require('./github-enterprise-app-repo-dependabot'),
    require('./github-enterprise-app-repo-markdown-files'),
    require('./github-enterprise-app-repo-yaml-files'),
    require('./github-enterprise-app-team-organization-members'),
    require('./gitlab-group-projects'),
    require('./gitlab-group-members'),
    require('./gitlab-project-members'),
    require('./gitlab-project-issues'),
    require('./gitlab-project-merge-requests'),
    require('./gitlab-project-pipelines'),
    require('./gitlab-project-environments'),
    require('./gitlab-group-groups'),
    require('./gitlab-group-ancestor-groups'),
    require('./gitlab-project-deployments'),
    require('./gitlab-project-tags'),
    require('./gitlab-project-releases'),
    require('./gitlab-environment-deployments'),
    require('./gitlab-tag-releases'),
    require('./circleci-pipeline-workflows'),
    require('./circleci-workflow-jobs'),
    require('./ado-project-repos'),
    require('./ado-project-pipelines'),
    require('./ado-project-pull-requests'),
    require('./ado-repo-pull-requests'),
    require('./ado-project-teams'),
    require('./ado-project-service-connections'),
    require('./ado-service-connection-azure-subscription'),
    require('./azure-subscription-resource-groups'),
    require('./azure-subscription-resources'),
    require('./azure-subscription-virtual-machines'),
    require('./azure-subscription-storage-accounts'),
    require('./azure-subscription-key-vaults'),
    require('./azure-subscription-managed-clusters'),
    require('./azure-resource-virtual-machines'),
    require('./azure-resource-storage-accounts'),
    require('./azure-resource-key-vaults'),
    require('./azure-resource-managed-clusters'),
    require('./entra-user-groups'),
    require('./entra-application-service-principals'),
    require('./entra-application-agent-identities'),
    require('./entra-domain-applications'),
    require('./entra-domain-users'),
    require('./msgraph-team-channels'),
    require('./msgraph-team-members'),
    require('./msgraph-team-member-entra-user'),
    require('./launchdarkly-project-flags'),
    require('./launchdarkly-project-environments'),
    require('./launchdarkly-project-metrics'),
    require('./launchdarkly-member-audit-log'),
    require('./launchdarkly-team-members'),
    require('./pagerduty-service-incidents'),
    require('./pagerduty-team-services'),
    require('./pagerduty-team-incidents'),
    require('./pagerduty-team-escalation-policies'),
    require('./pagerduty-escalation-policy-services'),
    require('./pagerduty-escalation-policy-incidents'),
    require('./pagerduty-escalation-policy-oncalls'),
    require('./pagerduty-user-oncalls'),
    require('./pagerduty-user-incidents'),
    require('./pagerduty-schedule-oncalls'),
    require('./snyk-organization-memberships'),
    require('./snyk-organization-targets'),
    require('./snyk-organization-projects'),
    require('./snyk-target-projects'),
    require('./shortcut-member-groups'),
    require('./shortcut-group-epics'),
    require('./shortcut-group-iterations'),
    require('./shortcut-project-epics'),
    require('./shortcut-iteration-epics'),
    require('./shortcut-member-owned-epics'),
    require('./shortcut-member-requested-epics'),
    require('./shortcut-member-followed-epics'),
    require('./entra-user-pagerduty-user'),
    require('./entra-user-launchdarkly-member'),
    require('./entra-user-shortcut-member'),
    require('./pagerduty-user-launchdarkly-member'),
    require('./pagerduty-user-shortcut-member'),
    require('./launchdarkly-member-shortcut-member'),
    require('./shortcut-member-github-user'),
    require('./entra-user-github-user'),
    require('./pagerduty-user-github-user'),
    require('./launchdarkly-member-github-user'),
    require('./humanitec-application-environments'),
    require('./pulumi-stack-deployments'),
    require('./datadog-monitor-creator-github-user'),
    require('./datadog-monitor-slos'),
    require('./datadog-team-memberships'),
    require('./dynatrace-synthetic-monitor-details'),
    require('./sentry-member-github-user'),
    require('./sentry-organization-members'),
    require('./sentry-organization-projects'),
    require('./sentry-organization-teams'),
    require('./sentry-project-issues'),
    require('./slack-user-entra-user'),
    require('./slack-user-github-user'),
    ...require('./slack-memberships'),
    require('./incident-incident-follow-ups'),
    require('./incident-user-github-user'),
    require('./incident-user-pagerduty-user'),
    require('./gcp-workspace-group-members'),
    require('./gcp-workspace-member-users'),
    require('./gcp-workspace-user-github-user'),
    require('./gcp-workspace-user-pagerduty-user'),
    require('./gcp-workspace-user-shortcut-member'),
    require('./okta-group-members'),
    require('./okta-user-github-user'),
    require('./okta-user-pagerduty-user'),
    require('./okta-user-shortcut-member'),
    require('./bitbucket-cloud-project-repositories'),
    require('./bitbucket-cloud-repo-pull-requests'),
    require('./bitbucket-cloud-workspace-members'),
    require('./bitbucket-cloud-workspace-projects'),
    require('./bitbucket-cloud-workspace-repositories'),
    require('./bitbucket-server-project-repositories'),
    require('./bitbucket-server-project-repositories-per-project'),
    require('./bitbucket-server-repo-pull-requests'),
    require('./bitbucket-server-user-github-user'),
    require('./anthropic-user-entra-user'),
    require('./anthropic-user-github-user'),
    ...require('./anthropic-workspace-memberships'),
    require('./cursor-member-github-user'),
    ...require('./cursor-usage'),
    require('./openai-project-api-keys'),
    require('./openai-project-members'),
    require('./openai-user-github-user'),
    ...require('./openai-project-context'),
    require('./gcp-resources-folder-projects'),
    require('./gcp-resources-organization-folders'),
    require('./gcp-resources-organization-projects'),
    require('./gcp-resources-organization-tag-keys'),
    ...require('./aws'),
    require('./jira-board-sprints'),
    require('./jira-project-issues'),
    require('./jira-user-github-user'),
    require('./linear-user-github-user'),
    require('./linear-user-shortcut-member'),
    ...require('./linear-issues-context'),
    require('./sonarqube-project-branches'),
    require('./sonarqube-project-issues'),
    require('./terraform-cloud-organization-workspaces'),
    require('./terraform-cloud-workspace-runs'),
    require('./terraform-cloud-workspace-github-repo'),
    require('./argocd-application-github-repo'),
    require('./argocd-cluster-applications'),
    require('./argocd-project-applications'),
    require('./buildkite-organization-pipelines'),
    require('./buildkite-organization-teams'),
    require('./buildkite-pipeline-builds'),
    ...require('./kubernetes-namespace-workloads'),
    ...require('./crossplane'),
    require('./wiz-project-issues'),
    ...require('./wiz-context'),
  ];
}

module.exports = { getRelationshipSeeds };
